
import { Device, License } from './types';
import dayjs from '../../../config/dayjsConfig';

export const mockDevices: Device[] = [
  {
    id: '1',
    name: 'Warehouse-Gateway-01',
    device_id: 'dev_829305_a',
    runtime_id: 'rt_v2_998',
    status: 'ONLINE',
    deployment_mode: 'EDGE',
    license_id: 'lic_001',
    license_name: 'Enterprise-Edge-V1',
    config_version: 'v2.4.1',
    last_seen_at: dayjs().subtract(2, 'minute').toISOString(),
    usage_image_count: 12050,
    usage_video_seconds: 400,
    region: 'us-east-1',
    tags: ['prod', 'warehouse'],
  },
  {
    id: '2',
    name: 'Assembly-Line-Cam',
    device_id: 'dev_112233_b',
    runtime_id: 'rt_v2_101',
    status: 'OFFLINE',
    deployment_mode: 'EDGE',
    license_id: 'lic_001',
    license_name: 'Enterprise-Edge-V1',
    config_version: 'v2.3.0',
    last_seen_at: dayjs().subtract(4, 'hour').toISOString(),
    usage_image_count: 0,
    usage_video_seconds: 0,
    region: 'us-west-2',
    tags: ['prod'],
  },
  {
    id: '3',
    name: 'New-Node-Pending',
    device_id: 'dev_new_unbound',
    runtime_id: 'rt_uninitialized',
    status: 'PENDING_LICENSE', // 触发待绑定逻辑
    deployment_mode: 'EDGE',
    license_id: undefined,
    license_name: undefined,
    config_version: 'N/A',
    last_seen_at: dayjs().subtract(5, 'minute').toISOString(),
    usage_image_count: 0,
    usage_video_seconds: 0,
    region: 'eu-central-1',
    tags: ['staging'],
  },
  {
    id: '4',
    name: 'Cloud-Runner-05',
    device_id: 'dev_cloud_555',
    runtime_id: 'rt_cloud_auto',
    status: 'ONLINE',
    deployment_mode: 'CLOUD',
    license_id: 'lic_cloud_99',
    license_name: 'Cloud-Scale-Standard',
    config_version: 'v2.5.0',
    last_seen_at: dayjs().subtract(1, 'minute').toISOString(),
    usage_image_count: 45000,
    usage_video_seconds: 12000,
    region: 'us-east-1',
    tags: ['cloud-fleet'],
  },
  {
    id: '5',
    name: 'Maintenance-Node-X',
    device_id: 'dev_maint_99',
    runtime_id: 'rt_maint_v1',
    status: 'DRAINING',
    deployment_mode: 'EDGE',
    license_id: 'lic_001',
    license_name: 'Enterprise-Edge-V1',
    config_version: 'v2.1.0',
    last_seen_at: dayjs().subtract(10, 'minute').toISOString(),
    usage_image_count: 100,
    usage_video_seconds: 0,
    region: 'us-east-1',
    tags: ['maintenance'],
  },
  {
    id: '6',
    name: 'Legacy-Server-08',
    device_id: 'dev_old_88',
    runtime_id: 'rt_legacy',
    status: 'DECOMMISSIONED',
    deployment_mode: 'EDGE',
    license_id: undefined,
    license_name: undefined,
    config_version: 'v1.0.0',
    last_seen_at: dayjs().subtract(1, 'month').toISOString(),
    usage_image_count: 0,
    usage_video_seconds: 0,
    region: 'ap-northeast-1',
    tags: ['archive'],
  },
  {
    id: '7',
    name: 'Faulty-Sensor-02',
    device_id: 'dev_error_02',
    runtime_id: 'rt_error',
    status: 'ERROR',
    deployment_mode: 'EDGE',
    license_id: 'lic_001',
    license_name: 'Enterprise-Edge-V1',
    config_version: 'v2.4.0',
    last_seen_at: dayjs().subtract(1, 'minute').toISOString(),
    usage_image_count: 0,
    usage_video_seconds: 0,
    region: 'us-east-1',
    tags: ['critical', 'error'],
  }
];

export const mockLicenses: License[] = [
  {
    id: 'lic_001',
    name: 'Enterprise-Edge-V1',
    license_key_masked: 'VF-EDGE-****-****-9988',
    type: 'SELF_HOSTED',
    billing_mode: 'per-device',
    used_devices: 2,
    total_quota: 10,
    expiry_date: dayjs().add(1, 'year').toISOString(),
    offline_lease_enabled: true,
  },
  {
    id: 'lic_cloud_99',
    name: 'Cloud-Scale-Standard',
    license_key_masked: 'VF-CLOUD-****-****-AABB',
    type: 'CLOUD',
    billing_mode: 'per-image',
    used_devices: 50,
    total_quota: 9999,
    expiry_date: dayjs().add(6, 'month').toISOString(),
    offline_lease_enabled: false,
  }
];
